[technote]
id = "ITTN-073"
series_id = "ITTN"
canonical_url = "https://ittn-073.lsst.io"
github_url = "https://github.com/lsst-it/ittn-073"
github_default_branch = "main"
date_created = 2024-01-31T17:07:57Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Joshua"
name.family = "Hoblitt"
internal_id = "hoblittj"
orcid = "https://orcid.org/0000-0002-5292-5879"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ  85719, USA"
